// Hierarchy Generation idiom: build a concrete class by chaining
// independent behavior policies through single inheritance, avoiding
// multiple inheritance entirely.
#include <iostream>

// Prototype for the hierarchy generator.
template <template <class> class... PolicyTs>
struct GenHierarchy;

// Recursive case: the head policy inherits from the hierarchy generated by
// the remaining (tail) policies, building a single-inheritance chain.
template <template <class> class HeadPolicyT,
          template <class> class... TailPolicyTs>
struct GenHierarchy<HeadPolicyT, TailPolicyTs...>
    : HeadPolicyT<GenHierarchy<TailPolicyTs...>> {};

// Terminator: no policies left, nothing to inherit from.
template <>
struct GenHierarchy<> {};

// Behavior policies: each contributes exactly one method to whatever
// eventually derives from it.
template <typename ParentT>
struct DanceA : ParentT {
  void Dance() { std::cout << "DanceA\n"; }
};
template <typename ParentT>
struct DanceB : ParentT {
  void Dance() { std::cout << "DanceB\n"; }
};
template <typename ParentT>
struct DanceC : ParentT {
  void Dance() { std::cout << "DanceC\n"; }
};

template <typename ParentT>
struct JokeA : ParentT {
  void Joke() { std::cout << "JokeA\n"; }
};
template <typename ParentT>
struct JokeB : ParentT {
  void Joke() { std::cout << "JokeB\n"; }
};
template <typename ParentT>
struct JokeC : ParentT {
  void Joke() { std::cout << "JokeC\n"; }
};

template <typename ParentT>
struct SongA : ParentT {
  void Sing() { std::cout << "SongA\n"; }
};
template <typename ParentT>
struct SongB : ParentT {
  void Sing() { std::cout << "SongB\n"; }
};
template <typename ParentT>
struct SongC : ParentT {
  void Sing() { std::cout << "SongC\n"; }
};

// Concrete entertainers, each a different combination of policies.
using BozoTheClown = GenHierarchy<DanceA, JokeB, SongC>;
using HowdyDoody = GenHierarchy<DanceB, JokeA, SongA>;
using RedButtons = GenHierarchy<DanceC, JokeC, SongB>;

template <typename EntertainerT>
void Entertain(EntertainerT entertainer) {
  entertainer.Sing();
  entertainer.Dance();
  entertainer.Joke();
}

int main() {
  std::cout << "-- BozoTheClown --\n";
  Entertain(BozoTheClown());
  std::cout << "-- HowdyDoody --\n";
  Entertain(HowdyDoody());
  std::cout << "-- RedButtons --\n";
  Entertain(RedButtons());
  return 0;
}
